#!/usr/bin/env bash
# Post-process Dark Reader color config generated by wallbash
# Saves colors as JSON and generates a .drconf preset for manual import

DARKREADER_JSON="${cacheDir:-$HOME/.cache/hyde}/wallbash/darkreader.json"
DRCONF_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/hyde/wallbash/darkreader.drconf"

if [ ! -f "$DARKREADER_JSON" ]; then
    exit 1
fi

# Extract colors from the generated JSON
dark_bg=$(jq -r '.darkreader.colors.darkSchemeBackgroundColor' "$DARKREADER_JSON" 2>/dev/null || echo "#000000")
dark_fg=$(jq -r '.darkreader.colors.darkSchemeTextColor' "$DARKREADER_JSON" 2>/dev/null || echo "#ffffff")
light_bg=$(jq -r '.darkreader.colors.lightSchemeBackgroundColor' "$DARKREADER_JSON" 2>/dev/null || echo "#ffffff")
light_fg=$(jq -r '.darkreader.colors.lightSchemeTextColor' "$DARKREADER_JSON" 2>/dev/null || echo "#000000")

# Generate a .drconf preset that can be imported into Dark Reader
cat > "$DRCONF_FILE" << EOF
Wallbash

DARK
background: ${dark_bg}
text: ${dark_fg}

LIGHT
background: ${light_bg}
text: ${light_fg}
EOF

# Print the settings so the darkreader.sh caller can see them
printf "Dark Reader colors updated:\n"
printf "  Dark BG: %s  Dark FG: %s\n" "$dark_bg" "$dark_fg"
printf "  Light BG: %s  Light FG: %s\n" "$light_bg" "$light_fg"
printf "  Config: %s\n" "$DRCONF_FILE"
