#!/usr/bin/env bash
# Post-process Dark Reader color config generated by wallbash
# 1. Saves colors as JSON (already done by wallbash)
# 2. Generates a .drconf preset for manual import
# 3. Tries to auto-apply via LevelDB if Brave is closed

DARKREADER_JSON="${cacheDir:-$HOME/.cache/hyde}/wallbash/darkreader.json"
DRCONF_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/hyde/wallbash/darkreader.drconf"
APPLY_SCRIPT="${WALLBASH_SCRIPTS:-${XDG_CONFIG_HOME:-$HOME/.config}/hyde/wallbash/scripts}/darkreader-apply.js"

if [ ! -f "$DARKREADER_JSON" ]; then
    exit 1
fi

# Generate a .drconf preset that can be imported into Dark Reader
dark_bg=$(jq -r '.darkreader.colors.darkSchemeBackgroundColor' "$DARKREADER_JSON" 2>/dev/null || echo "#000000")
dark_fg=$(jq -r '.darkreader.colors.darkSchemeTextColor' "$DARKREADER_JSON" 2>/dev/null || echo "#ffffff")
light_bg=$(jq -r '.darkreader.colors.lightSchemeBackgroundColor' "$DARKREADER_JSON" 2>/dev/null || echo "#ffffff")
light_fg=$(jq -r '.darkreader.colors.lightSchemeTextColor' "$DARKREADER_JSON" 2>/dev/null || echo "#000000")

cat > "$DRCONF_FILE" << EOF
Wallbash

DARK
background: ${dark_bg}
text: ${dark_fg}

LIGHT
background: ${light_bg}
text: ${light_fg}
EOF

# Try to auto-apply via LevelDB (only works when Brave is closed)
if command -v node &>/dev/null && [ -f "$APPLY_SCRIPT" ]; then
    APPLY_RESULT=$(node "$APPLY_SCRIPT" 2>&1)
    APPLY_EXIT=$?
    case $APPLY_EXIT in
        0)
            printf "Dark Reader auto-applied via LevelDB:\n"
            printf "  %s\n" "$APPLY_RESULT"
            ;;
        1)
            printf "No wallpaper colors yet.\n"
            ;;
        3)
            printf "Dark Reader colors saved (Brave is running - close Brave to apply).\n"
            printf "  Run: node %s\n" "$APPLY_SCRIPT"
            ;;
        *)
            printf "Dark Reader preset saved (auto-apply unavailable).\n"
            printf "  Config: %s\n" "$DRCONF_FILE"
            ;;
    esac
else
    printf "Dark Reader preset saved to %s\n" "$DRCONF_FILE"
    printf "Import in Dark Reader > Dev Tools to apply.\n"
fi
