#!/bin/bash

WALL_DCOL="${cacheDir:-$HOME/.cache/hyde}/wall.dcol"
WALLPAPER_SRC="${cacheDir:-$HOME/.cache/hyde}/wall.set.png"
WALL_SYM="${cacheDir:-$HOME/.cache/hyde}/wall.set"
SDDM_HELPER="/usr/local/bin/sddm-apply-wallbash"
TEMP_COLORS="/var/tmp/sddm-colors.conf"
TEMP_WALLPAPER="/var/tmp/sddm-bg"

# Read colors directly from HyDE's wall.dcol (always current)
if [ -f "$WALL_DCOL" ]; then
    . "$WALL_DCOL"
else
    echo "[wallbash] sddm :: No $WALL_DCOL — run wallbash first"
    exit 1
fi

[ -f "$WALLPAPER_SRC" ] || { echo "[wallbash] sddm :: No wallpaper at $WALLPAPER_SRC"; exit 1; }
[ -x "$SDDM_HELPER" ] || { echo "[wallbash] sddm :: Helper not found at $SDDM_HELPER"; exit 1; }

# Get basename from the actual wallpaper file (e.g., "car.png", "Wallpaper.jpg")
WALL_NAME=$(basename "$(readlink -f "$WALL_SYM" 2>/dev/null)" 2>/dev/null || echo "wallpaper")

# Generate sddm.conf with current wallpaper colors
cat > "$TEMP_COLORS" << EOF
# Autogenerated by sddm.sh from $WALL_DCOL
MainColor="#${dcol_txt1:-FFFFFF}"
AccentColor="#${dcol_1xa5:-6580A3}"
BackgroundColor="#${dcol_pry1:-132B4B}"
EOF

cp "$WALLPAPER_SRC" "$TEMP_WALLPAPER"

# Apply via sudo -n (NOPASSWD rule at /etc/sudoers.d/sddm-wallbash)
sudo -n "$SDDM_HELPER" "$TEMP_COLORS" "$TEMP_WALLPAPER" "$WALL_NAME" 2>/dev/null || {
    echo "[wallbash] sddm :: sudo -n failed. Is the NOPASSWD rule installed?"
    echo "[wallbash] sddm :: Run install.sh, or add:"
    echo "[wallbash] sddm ::   ${USER} ALL=(ALL) NOPASSWD: ${SDDM_HELPER}"
    echo "[wallbash] sddm :: to /etc/sudoers.d/sddm-wallbash"
    rm -f "$TEMP_COLORS" "$TEMP_WALLPAPER"
    exit 1
}

rm -f "$TEMP_COLORS" "$TEMP_WALLPAPER"
